module.exports = [
  {
    fileName: 'happy',
    synonyms: [
      'happy',
      'glad',
      'positive',
      'yay',
      'wee',
      'wew',
      'yey',
      'cute',
      'cutie',
    ],
  },
  {
    fileName: 'sad',
    synonyms: [
      'sad',
      'unhappy',
      'depressed',
      'cry',
      'crying',
      'depressed',
      'oh',
    ],
  },
  {
    fileName: 'angry',
    synonyms: [
      'angry',
      'annoyed',
      'bitter',
      'enraged',
      'exasperated',
      'furious',
      'heated',
      'impassioned',
      'indignant',
      'irate',
      'irritable',
      'irritated',
      'offended',
      'outraged',
      'resentful',
      'sullen',
      'uptight',
      'anger',
      'hangry',
      'sucks',
      'upset',
    ],
  },
  {
    fileName: 'cloud',
    synonyms: [
      'cloud',
      'darkness',
      'fog',
      'gloom',
      'mist',
      'puff',
      'smog',
      'smoke',
      'steam',
      'vapor',
      'veil',
    ],
  },
  {
    fileName: 'dog',
    synonyms: [
      'dog',
      'pup',
      'puppy',
      'cur',
      'doggy',
      'hound',
      'mongrel',
      'mutt',
      'pooch',
      'stray',
      'fido',
      'doggo',
      'pupper',
    ],
  },
  {
    fileName: 'food-drink',
    synonyms: [
      'food-drink',
      'cooking',
      'cook',
      'cuisine',
      'drink',
      'feed',
      'food',
      'foodstuff',
      'meal',
      'meat',
      'snack',
      'chow',
      'diet',
      'eats',
      'fodder',
      'grub',
      'tucker',
    ],
  },
  {
    fileName: 'hugging',
    synonyms: [
      'hugging',
      'hug',
      'affection',
      'caress',
      'hold',
    ],
  },
  {
    fileName: 'magic',
    synonyms: [
      'magic',
      'illusion',
      'alchemy',
      'astrology',
      'wizardry',
      'incantation',
      'conjure',
      'devilry',
      'voodoo',
      'witchcraft',
    ],
  },
  {
    fileName: 'objects',
    synonyms: [
      'objects',
      'object',
      'item',
      'gizmo',
      'gadget',
      'thingamajig',
      'rain',
      'umbrella',
      'pencil',
      'money',
      'scissors',
    ],
  },
  {
    fileName: 'rom',
    synonyms: [
      'rom',
    ],
  },
  {
    fileName: 'shy',
    synonyms: [
      'shy',
      'afraid',
      'apprehensive',
      'bashful',
      'cautious',
      'circumspect',
      'coy',
      'demure',
      'fearful',
      'hesitant',
      'humble',
      'modest',
      'nervous',
      'reluctant',
      'sheepish',
      'timid',
      'wary',
      'skittish',
    ],
  },
  {
    fileName: 'table-flipping',
    synonyms: [
      'table-flipping',
      'table',
      'flip',
      'riot',
      'flipped',
      'broken',
    ],
  },
  {
    fileName: 'worried',
    synonyms: [
      'worried',
      'bothered',
      'concerned',
      'distracted',
      'distressed',
      'disturbed',
      'frightened',
      'perturbed',
      'tense',
      'tormented',
      'upset',
    ],
  },
  {
    fileName: 'apologizing',
    synonyms: [
      'apologizing',
      'apologize',
      'apologise',
      'atone',
      'confess',
      'withdraw',
      'sorry',
      'whoops',
    ],
  },
  {
    fileName: 'confused',
    synonyms: [
      'confused',
      'baffled',
      'befuddled',
      'bewildered',
      'dazed',
      'disorganized',
      'disorganised',
      'eh?',
      'uhh',
    ],
  },
  {
    fileName: 'evil',
    synonyms: [
      'evil',
      'bad',
      'corrupt',
      'destructive',
      'hateful',
      'heinous',
      'hideous',
      'malevolent',
      'malicious',
      'nefarious',
      'unpleasant',
      'vile',
      'vicious',
      'wicked',
    ],
  },
  {
    fileName: 'friend',
    synonyms: [
      'friend',
      'buddy',
      'ally',
      'associate',
      'classmate',
      'colleague',
      'companion',
      'chum',
      'mate',
      'pal',
    ],
  },
  {
    fileName: 'hungry',
    synonyms: [
      'hungry',
      'starving',
      'ravenous',
      'hunger',
      'yum',
      'fork',
    ],
  },
  {
    fileName: 'meh',
    synonyms: [
      'meh',
      'whatever',
      'eh',
      'bleh',
      'dunno',
      'ehh',
    ],
  },
  {
    fileName: 'other-action',
    synonyms: [
      'other-action',
      'actions',
      'action',
      'tongue',
      'door',
      'peek a boo',
      'spit',
      'tv',
      'shower',
      'rocking',
      'marry',
      'marriage',
    ],
  },
  {
    fileName: 'running',
    synonyms: [
      'running',
      'run',
      'sprint',
      'race',
      'rush',
      'jog',
      'gallop',
    ],
  },
  {
    fileName: 'sleeping',
    synonyms: [
      'sleeping',
      'sleep',
      'snooze',
      'slumber',
      'dream',
      'hibernation',
      'coma',
      'nap',
      'catnap',
      'doze',
      'bedtime',
      'bed',
      'sleepy',
      'tired',
      'exhausted',
    ],
  },
  {
    fileName: 'thinking',
    synonyms: [
      'thinking',
      'think',
      'ponder',
      'pondering',
      'deliberate',
      'deliberating',
      'meditate',
    ],
  },
  {
    fileName: 'writing',
    synonyms: [
      'writing',
      'write',
      'compose',
      'draft',
      'note',
      'record',
      'letter',
      'scrawl',
      'inscribe',
    ],
  },
  {
    fileName: 'bear',
    synonyms: [
      'bear',
      'grizzly',
    ],
  },
  {
    fileName: 'crazy',
    synonyms: [
      'crazy',
      'insane',
      'kooky',
      'mad',
      'nuts',
      'nutty',
      'wacky',
      'lunatic',
      'cuckoo',
      'berserk',
    ],
  },
  {
    fileName: 'excited',
    synonyms: [
      'excited',
      'agitated',
      'eager',
      'enthusiastic',
      'thrilled',
      'woo!',
    ],
  },
  {
    fileName: 'giving-up',
    synonyms: [
      'giving-up',
      'giveup',
      'failure',
    ],
  },
  {
    fileName: 'hurt-or-sick',
    synonyms: [
      'hurt-or-sick',
      'hurt',
      'sick',
      'ill',
      'ouch',
      'ow',
    ],
  },
  {
    fileName: 'monkey',
    synonyms: [
      'monkey',
      'chimp',
      'ape',
      'orangutan',
    ],
  },
  {
    fileName: 'other-animal',
    synonyms: [
      'other-animal',
      'animal',
    ],
  },
  {
    fileName: 'smug',
    synonyms: [
      'smug',
      'pompous',
      'superior',
      'huehuehue',
      'hyuk',
    ],
  },
  {
    fileName: 'triumph-success',
    synonyms: [
      'triumph-success',
      'winning',
      'win',
      'winner',
      'success',
      'victory',
      'awesome',
      'rad',
      'cool',
      'neat',
      'celebrate',
      'merge',
    ],
  },
  {
    fileName: 'wtf',
    synonyms: [
      'wtf',
      'wat',
      'nsfw',
    ],
  },
  {
    fileName: 'bird',
    synonyms: [
      'bird',
      'avian',
      'duck',
      'chick',
      'chicken',
      'hawk',
      'crow',
      'eagle',
      'pidgeon',
    ],
  },
  {
    fileName: 'crying',
    synonyms: [
      'crying',
      'cry',
      'sob',
      'howl',
      'bawl',
      'tears',
    ],
  },
  {
    fileName: 'fighting-weapons-violent',
    synonyms: [
      'fighting-weapons-violent',
      'weapons',
      'sword',
      'fight',
      'battle',
    ],
  },
  {
    fileName: 'kissing',
    synonyms: [
      'kissing',
      'kiss',
      'smooch',
      'peck',
    ],
  },
  {
    fileName: 'music',
    synonyms: [
      'music',
      'tunes',
      'toons',
      'rock',
      'dance',
    ],
  },
  {
    fileName: 'other',
    synonyms: [
      'other',
    ],
  },
  {
    fileName: 'saluting',
    synonyms: [
      'saluting',
      'salute',
      'review',
      'pull request',
      'roger',
      'righto',
      'affirmative',
      'gotcha',
      'commit',
      'request',
      'ready',
      'pr',
    ],
  },
  {
    fileName: 'sports-related',
    synonyms: [
      'sports-related',
      'sports',
      'sport',
      'sportsball',
    ],
  },
  {
    fileName: 'waving',
    synonyms: [
      'waving',
      'wave',
      'hi',
      'bye',
      'bai',
      'hello',
      'hey',
      'welcome',
      'ciao',
      'morning',
      'evening',
      'afternoon',
      'heya',
      'arvo',
    ],
  },
  {
    fileName: 'cat',
    synonyms: [
      'cat',
      'feline',
      'pussy',
      'kitty',
      'kitten',
      'demon',
      'kitteh',
    ],
  },
  {
    fileName: 'dancing',
    synonyms: [
      'dancing',
      'dance',
      'disco',
      'samba',
      'tango',
      'waltz',
      'jig',
      'twist',
      'rhumba',
      'jitter',
    ],
  },
  {
    fileName: 'fish',
    synonyms: [
      'fish',
      'fishing',
      'angle',
      'bait',
    ],
  },
  {
    fileName: 'hiding',
    synonyms: [
      'hiding',
      'hide',
      'shelter',
      'protect',
      'shield',
    ],
  },
  {
    fileName: 'laughing',
    synonyms: [
      'laughing',
      'laugh',
      'chuckle',
      'giggle',
      'grin',
      'lol',
      'rofl',
      'roflmao',
      'heh',
      'ha',
    ],
  },
  {
    fileName: 'mustache',
    synonyms: [
      'mustache',
      'beard',
      'goatee',
      'sideburns',
      'stubble',
      'bristles',
    ],
  },
  {
    fileName: 'pig',
    synonyms: [
      'pig',
      'pork',
      'oink',
      'cop',
      'cops',
      'police',
      'policeman',
    ],
  },
  {
    fileName: 'scared',
    synonyms: [
      'scared',
      'terrified',
      'anxious',
      'panicked',
      'petrified',
      'scary',
      'terror',
      'hiding',
    ],
  },
  {
    fileName: 'sunglasses',
    synonyms: [
      'sunglasses',
      'sunnies',
      'sun',
      'glasses',
      'spectacles',
      'deal with it',
      'specs',
      'shades',
    ],
  },
  {
    fileName: 'winking',
    synonyms: [
      'winking',
      'wink',
      'twinkle',
      'gleam',
      'glimmer',
    ],
  },
  {
    fileName: 'character-meme',
    synonyms: [
      'character-meme',
      'meme',
      'pikachu',
      'snorlax',
      'hindsight',
      'weedle',
      'wooper',
      'point out',
      'picard',
    ],
  },
  {
    fileName: 'dead',
    synonyms: [
      'dead',
      'death',
      'deceased',
      'lifeless',
      'buried',
      'late',
      'departed',
      'stiff',
      'ded',
    ],
  },
  {
    fileName: 'flexing',
    synonyms: [
      'flexing',
      'flex',
      'muscles',
      'strong',
      'gym',
      'lift',
      'lifting',
    ],
  },
  {
    fileName: 'holiday',
    synonyms: [
      'holiday',
      'vacation',
      'relax',
      'relaxing',
      'christmas',
      'new year',
      'birthday',
      'valentines',
    ],
  },
  {
    fileName: 'love',
    synonyms: [
      'love',
      'devotion',
      'fondness',
      'stricken',
      'lust',
      'passion',
      'tender',
      'tenderness',
      'yearning',
    ],
  },
  {
    fileName: 'nose-bleed',
    synonyms: [
      'nose-bleed',
      'nose',
      'bleed',
      'nosebleed',
      'hnng',
      'hnnng',
    ],
  },
  {
    fileName: 'rabbit',
    synonyms: [
      'rabbit',
      'hare',
      'bunny',
      'bunnies',
      'rodent',
      'bugs',
    ],
  },
  {
    fileName: 'sheep',
    synonyms: [
      'sheep',
      'ewe',
      'lamb',
    ],
  },
  {
    fileName: 'surprised',
    synonyms: [
      'surprised',
      'surprise',
      'amazement',
      'astonished',
      'awe',
      'miracle',
      'revelation',
      'wonder',
      'shock',
    ],
  },
  {
    fileName: 'words',
    synonyms: [
      'words',
      'word',
      'letter',
      'letters',
      'language',
    ],
  },
];
