/* eslint quote-props: 0 */
module.exports = {
  'happy': ['happy', 'glad', 'positive', 'yay'],
  'sad': ['sad', 'unhappy', 'depressed', 'cry', 'crying', 'depressed'],
  'angry': ['angry', 'annoyed', 'bitter', 'enraged', 'exasperated', 'furious', 'heated', 'impassioned', 'indignant', 'irate', 'irritable', 'irritated', 'offended', 'outraged', 'resentful', 'sullen', 'uptight'],
  'cloud': ['cloud', 'darkness', 'fog', 'gloom', 'mist', 'puff', 'smog', 'smoke', 'steam', 'vapor', 'veil'],
  'dog': ['dog', 'pup', 'puppy', 'bitch', 'cur', 'doggy', 'hound', 'mongrel', 'mutt', 'pooch', 'stray', 'fido'],
  'food-drink': ['food-drink', 'cooking', 'cook', 'cuisine', 'drink', 'feed', 'food', 'foodstuff', 'meal', 'meat', 'snack', 'chow', 'diet', 'eats', 'fodder', 'grub', 'tucker'],
  'hugging': ['hugging', 'hug', 'affection', 'caress', 'hold'],
  'magic': ['magic', 'illusion', 'alchemy', 'astrology', 'wizardry', 'incantation', 'conjure', 'devilry', 'voodoo', 'witchcraft'],
  'objects': ['objects', 'object', 'item', 'gizmo', 'gadget', 'thingamajig'],
  'rom': ['rom'],
  'shy': ['shy', 'afraid', 'apprehensive', 'bashful', 'cautious', 'circumspect', 'coy', 'demure', 'fearful', 'hesitant', 'humble', 'modest', 'nervous', 'reluctant', 'sheepish', 'timid', 'wary', 'skittish'],
  'table-flipping': ['table-flipping', 'table-flip', 'table', 'flip', 'riot'],
  'worried': ['worried', 'bothered', 'concerned', 'distracted', 'distressed', 'disturbed', 'frightened', 'perturbed', 'tense', 'tormented', 'upset'],
  'apologizing': ['apologizing', 'apologize', 'apologise', 'atone', 'confess', 'withdraw'],
  'confused': ['confused', 'baffled', 'befuddled', 'bewildered', 'dazed', 'disorganized', 'disorganised'],
  'evil': ['evil', 'bad', 'corrupt', 'destructive', 'hateful', 'heinous', 'hideous', 'malevolent', 'malicious', 'nefarious', 'unpleasant', 'vile', 'vicious', 'wicked'],
  'friend': ['friend', 'buddy', 'ally', 'associate', 'classmate', 'colleague', 'companion', 'chum', 'mate', 'pal'],
  'hungry': ['hungry', 'starving', 'ravenous'],
  'meh': ['meh'],
  'other-action': ['other-action', 'actions', 'action'],
  'running': ['running', 'run', 'sprint', 'race', 'rush', 'jog', 'gallop'],
  'sleeping': ['sleeping', 'sleep', 'snooze', 'slumber', 'dream', 'hibernation', 'coma', 'nap', 'catnap', 'doze', 'bedtime', 'bed'],
  'thinking': ['thinking', 'think', 'ponder', 'pondering', 'deliberate', 'deliberating', 'meditate'],
  'writing': ['writing', 'write', 'compose', 'draft', 'note', 'record', 'letter', 'scrawl', 'inscribe'],
  'bear': ['bear'],
  'crazy': ['crazy', 'insane', 'kooky', 'mad', 'nuts', 'nutty', 'wacky', 'lunatic', 'cuckoo', 'berserk'],
  'excited': ['excited', 'agitated', 'eager', 'enthusiastic', 'thrilled'],
  'giving-up': ['giving-up'],
  'hurt-or-sick': ['hurt-or-sick', 'hurt', 'sick', 'ill', 'ouch'],
  'monkey': ['monkey'],
  'other-animal': ['other-animal'],
  'smug': ['smug', 'complacent', 'egotistical', 'pompous', 'superior'],
  'triumph-success': ['triumph-success'],
  'wtf': ['wtf'],
  'bird': ['bird', 'avian', 'duck', 'chick', 'chicken', 'hawk', 'crow', 'eagle', 'pidgeon'],
  'crying': ['crying', 'cry', 'sob', 'howl', 'bawl', 'tears'],
  'fighting-weapons-violent': ['fighting-weapons-violent', 'weapons', 'sword', 'fight', 'battle'],
  'kissing': ['kissing', 'kiss', 'smooch', 'peck'],
  'music': ['music', 'tunes', 'toons', 'rock', 'dance'],
  'other': ['other'],
  'saluting': ['saluting'],
  'sports-related': ['sports-related', 'sports', 'sport'],
  'waving': ['waving'],
  'cat': ['cat'],
  'dancing': ['dancing'],
  'fish': ['fish'],
  'hiding': ['hiding'],
  'laughing': ['laughing'],
  'mustache': ['mustache'],
  'pig': ['pig'],
  'scared': ['scared'],
  'sunglasses': ['sunglasses'],
  'winking': ['winking'],
  'character-meme': ['character-meme'],
  'dead': ['dead'],
  'flexing': ['flexing'],
  'holiday': ['holiday'],
  'love': ['love'],
  'nose-bleed': ['nose-bleed'],
  'rabbit': ['rabbit'],
  'sheep': ['sheep'],
  'surprised': ['surprised'],
  'words': ['words'],
};
